// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkOZg0cqCbnvgYLuQ2FOzxPxIgpu14We0',
    appId: '1:303383910806:web:306015179f825f3fabe5b7',
    messagingSenderId: '303383910806',
    projectId: 'uasmobile-kelompok4-d7559',
    authDomain: 'uasmobile-kelompok4-d7559.firebaseapp.com',
    storageBucket: 'uasmobile-kelompok4-d7559.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmy147chJWjm23bC2Zej1DazZ22iJKgmQ',
    appId: '1:303383910806:android:6e90881da93c1f18abe5b7',
    messagingSenderId: '303383910806',
    projectId: 'uasmobile-kelompok4-d7559',
    storageBucket: 'uasmobile-kelompok4-d7559.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0fbzebJgZDvG7JR0q9xtUJyyXpFrrFKU',
    appId: '1:303383910806:ios:54750206709c51bdabe5b7',
    messagingSenderId: '303383910806',
    projectId: 'uasmobile-kelompok4-d7559',
    storageBucket: 'uasmobile-kelompok4-d7559.firebasestorage.app',
    iosBundleId: 'com.example.uasmobileKelompok4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0fbzebJgZDvG7JR0q9xtUJyyXpFrrFKU',
    appId: '1:303383910806:ios:54750206709c51bdabe5b7',
    messagingSenderId: '303383910806',
    projectId: 'uasmobile-kelompok4-d7559',
    storageBucket: 'uasmobile-kelompok4-d7559.firebasestorage.app',
    iosBundleId: 'com.example.uasmobileKelompok4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkOZg0cqCbnvgYLuQ2FOzxPxIgpu14We0',
    appId: '1:303383910806:web:af5eb01f0ce11747abe5b7',
    messagingSenderId: '303383910806',
    projectId: 'uasmobile-kelompok4-d7559',
    authDomain: 'uasmobile-kelompok4-d7559.firebaseapp.com',
    storageBucket: 'uasmobile-kelompok4-d7559.firebasestorage.app',
  );
}
